#!/usr/bin/env bash
# To install run: cp .githooks/pre-push .git/hooks/pre-push

# Exit with code 1 if any command fails
set -euo pipefail
trap 'exit 1' ERR

# Run unit tests
poetry run pytest

# Test with test packages locally
poetry run python -m ossprey --dry-run-safe --package test/npm_simple_math/ --mode npm
poetry run python -m ossprey --dry-run-safe --package test/yarn_simple_math/ --mode yarn
poetry run python -m ossprey --dry-run-safe --package test/yarn_massive_math/ --mode yarn
poetry run python -m ossprey --dry-run-safe --package test/python_simple_math/ --mode python-requirements
poetry run python -m ossprey --dry-run-malicious --package test/npm_simple_math/ --mode npm
